#https://docs.gitlab.com/omnibus/docker/README.html was used as base for this file
version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'gitlab.staging.teco.edu'
    environment:
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       VIRTUAL_PORT: ${VIRTUAL_PORT}
       LETSENCRYPT_HOST: ${VIRTUAL_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
       # Add any other gitlab.rb configuration here, each on its own line
       GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.staging.teco.edu'
        gitlab_rails['git_timeout'] = 600
        nginx['keepalive_timeout'] = 300
        unicorn['worker_timeout'] = 300                        #to reduce effect of network glitches
        unicorn['worker_processes'] = 3  
        nginx['listen_port'] = 80
       # nginx['redirect_http_to_https'] = true
       #nginx['proxy_set_headers'] = {
       #"X-Forwarded-Proto" => "https",
       #"X-Forwarded-Ssl" => "on"
       #}
    expose:
      - '80'
    volumes:
      - '/srv/business-essentials/teco_gitlab/config:/etc/gitlab'
      - '/srv/business-essentials/teco_gitlab/logs:/var/log/gitlab'
      - '/srv/business-essentials/teco_gitlab/data:/var/opt/gitlab'
    networks:
      - nginx-proxy
      
networks:
  nginx-proxy:
    external: true
