#https://docs.gitlab.com/omnibus/docker/README.html was used as base for this file
version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:9.5.4-ce.0
    container_name: gitlab
    restart: always
    environment:
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       VIRTUAL_PORT: ${VIRTUAL_PORT}
       LETSENCRYPT_HOST: ${VIRTUAL_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
       # Add any other gitlab.rb configuration here, each on its own line
       GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${VIRTUAL_HOST}'
        gitlab_rails['git_timeout'] = 600
        nginx['keepalive_timeout'] = 300
        unicorn['worker_timeout'] = 300                        #to reduce effect of network glitches
        unicorn['worker_processes'] = 3  
        nginx['listen_port'] = 80
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-EOS
         main:
          label: 'LDAP'
          host: 'www.zflexldap.com'
          port: 389
          uid: 'uid'     
          bind_dn: 'cn=ro_admin,ou=sysadmins,dc=zflexsoftware,dc=com'
          password: 'zflexpass'
          active_directory: false
          base: 'dc=zflexsoftware,dc=com'
          method: 'plain' 
          EOS
       # nginx['redirect_http_to_https'] = true
       #nginx['proxy_set_headers'] = {
       #"X-Forwarded-Proto" => "https",
       #"X-Forwarded-Ssl" => "on"
       #}
       
    expose:
      - '80'
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    networks:
      - nginx-proxy
      
networks:
  nginx-proxy:
    external: true

volumes:
  config:
  logs:
  data:
