#https://docs.gitlab.com/omnibus/docker/README.html was used as base for this file
version: '3'
services:
  gitlab:
    build: .
    container_name: gitlab
    restart: always
    environment:
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       VIRTUAL_PORT: ${VIRTUAL_PORT}
       LETSENCRYPT_HOST: ${VIRTUAL_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
       # Add any other gitlab.rb configuration here, each on its own line
       GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${VIRTUAL_HOST}'
        gitlab_rails['git_timeout'] = 600
        nginx['keepalive_timeout'] = 300
        unicorn['worker_timeout'] = 300                        #to reduce effect of network glitches
        unicorn['worker_processes'] = 3  
        nginx['listen_port'] = 80
        gitlab_rails['omniauth_enabled'] = true;
        gitlab_rails['omniauth_allow_single_sign_on'] = true;
        gitlab_rails['omniauth_block_auto_created_users'] = false;
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'Keycloak'; 
        gitlab_rails['omniauth_providers'] = [{'name'=>'openid_connect', 'args'=>{'name'=>'Keycloak', 'scope'=>['openid', 'profile'], 'response_type'=>'code', 'discovery'=>true, 'issuer'=>'${ISSUER_URL}', 'client_options'=>{'port'=>'80', 'scheme'=>'https', 'host'=>'${IDP_HOSTNAME}', 'identifier'=>'${CLIENT_ID}', 'secret'=>'${CLIENT_SECRET}', 'redirect_uri'=>'https://${VIRTUAL_HOST}/users/auth/Keycloak/callback'}}}];
       
    expose:
      - '80'
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    networks:
      - keycloak_services
      - nginx-proxy
      
networks:
  keycloak_services:
    external: true
  nginx-proxy:
    external: true

volumes:
  config:
  logs:
  data:
